version: '3'

services:
  web:
    container_name: nodejs18
    restart: always
    build: . 
    ports:
      - 3002:3000  
    environment:
      - MONGODB_URL=mongodb://mongodb:27017/nombre_base_datos  
    networks:
      - mynetwork

  mongo:  
    container_name: mongodb  
    image: mongo  
    ports:
      - 27017:27017  
    volumes:
      - mongo-data:/data/db  
    networks:
      - mynetwork  

volumes:
  mongo-data:  

networks:
  mynetwork:  
    driver: bridge  
